# Generated by Django 4.2.2 on 2023-06-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('lunch_api', '0003_remove_vote_employee_remove_vote_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_api.menu')),
            ],
        ),
    ]
