# Generated by Django 4.2.2 on 2023-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
