# Generated by Django 4.2.2 on 2023-06-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_api', '0002_vote_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
